name: Check Lua Formatting
on:
  pull_request:
    branches:
      - master
      - main
      - feature/*
      - hotfix/*
      - release/*

jobs:
  Stylua Check:
    uses: JohnnyMorganz/stylua-action@v3
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      version: latest
      args: --check .

